/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Administrator' at '19-6-1 上午10:07' with Gradle 2.14.1
 *
 * @author Administrator, @date 19-6-1 上午10:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
